const detail = [
  {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 16,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 209,
    healthScore: 18,
    creditsText: "Full Belly Sisters",
    license: "CC BY-SA 3.0",
    sourceName: "Full Belly Sisters",
    pricePerServing: 157.06,
    extendedIngredients: [
      {
        id: 1001,
        aisle: "Milk, Eggs, Other Dairy",
        image: "butter-sliced.jpg",
        consistency: "SOLID",
        name: "butter",
        nameClean: "butter",
        original: "1 tbsp butter",
        originalName: "butter",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 10011135,
        aisle: "Produce",
        image: "cauliflower.jpg",
        consistency: "SOLID",
        name: "cauliflower florets",
        nameClean: "cauliflower florets",
        original:
          "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
        originalName:
          "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
        amount: 2.0,
        unit: "cups",
        meta: ["frozen", "thawed", "cut into bite-sized pieces"],
        measures: {
          us: { amount: 2.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 200.0, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1038,
        aisle: "Cheese",
        image: "parmesan.jpg",
        consistency: "SOLID",
        name: "cheese",
        nameClean: "pecorino romano",
        original: "2 tbsp grated cheese (I used romano)",
        originalName: "grated cheese (I used romano)",
        amount: 2.0,
        unit: "tbsp",
        meta: ["grated", "(I used romano)"],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 1034053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "LIQUID",
        name: "extra virgin olive oil",
        nameClean: "extra virgin olive oil",
        original: "1-2 tbsp extra virgin olive oil",
        originalName: "extra virgin olive oil",
        amount: 1.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "5-6 cloves garlic",
        originalName: "garlic",
        amount: 5.0,
        unit: "cloves",
        meta: [],
        measures: {
          us: { amount: 5.0, unitShort: "cloves", unitLong: "cloves" },
          metric: { amount: 5.0, unitShort: "cloves", unitLong: "cloves" },
        },
      },
      {
        id: 10720420,
        aisle: "Pasta and Rice",
        image: "spaghetti.jpg",
        consistency: "SOLID",
        name: "pasta",
        nameClean: "linguine",
        original: "6-8 ounces pasta (I used linguine)",
        originalName: "pasta (I used linguine)",
        amount: 6.0,
        unit: "ounces",
        meta: ["(I used linguine)"],
        measures: {
          us: { amount: 6.0, unitShort: "oz", unitLong: "ounces" },
          metric: { amount: 170.097, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 1032009,
        aisle: "Spices and Seasonings",
        image: "red-pepper-flakes.jpg",
        consistency: "SOLID",
        name: "couple of pepper flakes",
        nameClean: "red pepper flakes",
        original: "couple of pinches red pepper flakes, optional",
        originalName: "couple of red pepper flakes, optional",
        amount: 2.0,
        unit: "pinches",
        meta: ["red"],
        measures: {
          us: { amount: 2.0, unitShort: "pinches", unitLong: "pinches" },
          metric: { amount: 2.0, unitShort: "pinches", unitLong: "pinches" },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "salt and pepper, to taste",
        originalName: "salt and pepper, to taste",
        amount: 2.0,
        unit: "servings",
        meta: ["to taste"],
        measures: {
          us: { amount: 2.0, unitShort: "servings", unitLong: "servings" },
          metric: { amount: 2.0, unitShort: "servings", unitLong: "servings" },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "scallions",
        nameClean: "spring onions",
        original: "3 scallions, chopped, white and green parts separated",
        originalName: "scallions, chopped, white and green parts separated",
        amount: 3.0,
        unit: "",
        meta: ["white", "green", "separated", "chopped"],
        measures: {
          us: { amount: 3.0, unitShort: "", unitLong: "" },
          metric: { amount: 3.0, unitShort: "", unitLong: "" },
        },
      },
      {
        id: 14106,
        aisle: "Alcoholic Beverages",
        image: "white-wine.jpg",
        consistency: "LIQUID",
        name: "white wine",
        nameClean: "dry white wine",
        original: "2-3 tbsp white wine",
        originalName: "white wine",
        amount: 2.0,
        unit: "tbsp",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 2.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 99025,
        aisle: "Pasta and Rice",
        image: "breadcrumbs.jpg",
        consistency: "SOLID",
        name: "bread crumbs",
        nameClean: "whole wheat breadcrumbs",
        original: "1/4 cup whole wheat bread crumbs (I used panko)",
        originalName: "whole wheat bread crumbs (I used panko)",
        amount: 0.25,
        unit: "cup",
        meta: ["whole wheat", "(I used panko)"],
        measures: {
          us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 27.0, unitShort: "g", unitLong: "grams" },
        },
      },
    ],
    id: 716429,
    title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    readyInMinutes: 45,
    servings: 2,
    sourceUrl:
      "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
    image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
    imageType: "jpg",
    nutrition: {
      nutrients: [
        {
          name: "Calories",
          amount: 543.36,
          unit: "kcal",
          percentOfDailyNeeds: 27.17,
        },
        { name: "Fat", amount: 16.2, unit: "g", percentOfDailyNeeds: 24.93 },
        {
          name: "Saturated Fat",
          amount: 5.85,
          unit: "g",
          percentOfDailyNeeds: 36.57,
        },
        {
          name: "Carbohydrates",
          amount: 83.7,
          unit: "g",
          percentOfDailyNeeds: 27.9,
        },
        {
          name: "Net Carbohydrates",
          amount: 76.97,
          unit: "g",
          percentOfDailyNeeds: 27.99,
        },
        { name: "Sugar", amount: 5.32, unit: "g", percentOfDailyNeeds: 5.91 },
        {
          name: "Cholesterol",
          amount: 20.47,
          unit: "mg",
          percentOfDailyNeeds: 6.82,
        },
        {
          name: "Sodium",
          amount: 413.23,
          unit: "mg",
          percentOfDailyNeeds: 17.97,
        },
        { name: "Alcohol", amount: 1.55, unit: "g", percentOfDailyNeeds: 8.58 },
        {
          name: "Protein",
          amount: 16.84,
          unit: "g",
          percentOfDailyNeeds: 33.68,
        },
        {
          name: "Selenium",
          amount: 56.36,
          unit: "µg",
          percentOfDailyNeeds: 80.51,
        },
        {
          name: "Vitamin C",
          amount: 56.62,
          unit: "mg",
          percentOfDailyNeeds: 68.64,
        },
        {
          name: "Manganese",
          amount: 1.11,
          unit: "mg",
          percentOfDailyNeeds: 55.49,
        },
        {
          name: "Vitamin K",
          amount: 57.96,
          unit: "µg",
          percentOfDailyNeeds: 55.2,
        },
        { name: "Fiber", amount: 6.73, unit: "g", percentOfDailyNeeds: 26.92 },
        {
          name: "Phosphorus",
          amount: 265.58,
          unit: "mg",
          percentOfDailyNeeds: 26.56,
        },
        {
          name: "Folate",
          amount: 84.79,
          unit: "µg",
          percentOfDailyNeeds: 21.2,
        },
        {
          name: "Vitamin B6",
          amount: 0.42,
          unit: "mg",
          percentOfDailyNeeds: 21.14,
        },
        {
          name: "Magnesium",
          amount: 69.4,
          unit: "mg",
          percentOfDailyNeeds: 17.35,
        },
        {
          name: "Potassium",
          amount: 587.13,
          unit: "mg",
          percentOfDailyNeeds: 16.78,
        },
        { name: "Iron", amount: 3.0, unit: "mg", percentOfDailyNeeds: 16.68 },
        {
          name: "Copper",
          amount: 0.33,
          unit: "mg",
          percentOfDailyNeeds: 16.27,
        },
        {
          name: "Calcium",
          amount: 123.17,
          unit: "mg",
          percentOfDailyNeeds: 12.32,
        },
        { name: "Zinc", amount: 1.78, unit: "mg", percentOfDailyNeeds: 11.9 },
        {
          name: "Vitamin B5",
          amount: 1.13,
          unit: "mg",
          percentOfDailyNeeds: 11.28,
        },
        {
          name: "Vitamin B3",
          amount: 2.13,
          unit: "mg",
          percentOfDailyNeeds: 10.67,
        },
        {
          name: "Vitamin B1",
          amount: 0.15,
          unit: "mg",
          percentOfDailyNeeds: 10.31,
        },
        {
          name: "Vitamin E",
          amount: 1.5,
          unit: "mg",
          percentOfDailyNeeds: 10.01,
        },
        {
          name: "Vitamin B2",
          amount: 0.16,
          unit: "mg",
          percentOfDailyNeeds: 9.28,
        },
        {
          name: "Vitamin A",
          amount: 407.96,
          unit: "IU",
          percentOfDailyNeeds: 8.16,
        },
        {
          name: "Vitamin B12",
          amount: 0.07,
          unit: "µg",
          percentOfDailyNeeds: 1.13,
        },
      ],
      properties: [
        { name: "Glycemic Index", amount: 114.0, unit: "" },
        { name: "Glycemic Load", amount: 27.56, unit: "" },
        { name: "Nutrition Score", amount: 22.085652173913044, unit: "%" },
      ],
      flavonoids: [
        { name: "Cyanidin", amount: 0.0, unit: "mg" },
        { name: "Petunidin", amount: 0.0, unit: "" },
        { name: "Delphinidin", amount: 0.0, unit: "" },
        { name: "Malvidin", amount: 0.01, unit: "mg" },
        { name: "Pelargonidin", amount: 0.0, unit: "" },
        { name: "Peonidin", amount: 0.0, unit: "" },
        { name: "Catechin", amount: 0.12, unit: "mg" },
        { name: "Epigallocatechin", amount: 0.0, unit: "mg" },
        { name: "Epicatechin", amount: 0.08, unit: "mg" },
        { name: "Epicatechin 3-gallate", amount: 0.0, unit: "mg" },
        { name: "Epigallocatechin 3-gallate", amount: 0.0, unit: "mg" },
        { name: "Theaflavin", amount: 0.0, unit: "" },
        { name: "Thearubigins", amount: 0.0, unit: "" },
        { name: "Eriodictyol", amount: 0.0, unit: "" },
        { name: "Hesperetin", amount: 0.06, unit: "mg" },
        { name: "Naringenin", amount: 0.06, unit: "mg" },
        { name: "Apigenin", amount: 0.04, unit: "mg" },
        { name: "Luteolin", amount: 0.1, unit: "mg" },
        { name: "Isorhamnetin", amount: 0.0, unit: "mg" },
        { name: "Kaempferol", amount: 0.63, unit: "mg" },
        { name: "Myricetin", amount: 0.12, unit: "mg" },
        { name: "Quercetin", amount: 2.6, unit: "mg" },
        { name: "Theaflavin-3,3'-digallate", amount: 0.0, unit: "" },
        { name: "Theaflavin-3'-gallate", amount: 0.0, unit: "" },
        { name: "Theaflavin-3-gallate", amount: 0.0, unit: "" },
        { name: "Gallocatechin", amount: 0.0, unit: "mg" },
      ],
      ingredients: [
        {
          id: 1001,
          name: "butter",
          amount: 0.5,
          unit: "tbsp",
          nutrients: [
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Sodium",
              amount: 45.65,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Vitamin A",
              amount: 177.43,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Fluoride",
              amount: 0.2,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 1.7,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.5,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.16,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 1.7,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 50.91,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 1.49,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 1.33,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.21,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Trans Fat",
              amount: 0.23,
              unit: "g",
              percentOfDailyNeeds: 2327.38,
            },
            {
              name: "Magnesium",
              amount: 0.14,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 5.76,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.06,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.22,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 15.27,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.01,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 1.7,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.07,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Saturated Fat",
              amount: 3.65,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Vitamin B5",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 10011135,
          name: "cauliflower florets",
          amount: 1.0,
          unit: "cups",
          nutrients: [
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Sodium",
              amount: 30.0,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Fluoride",
              amount: 1.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Iron",
              amount: 0.42,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.06,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 44.0,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 48.2,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.16,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 15.5,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.27,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.18,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.08,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 299.0,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 2.0,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 25.0,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 1.91,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Net Carbohydrates",
              amount: 2.97,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.03,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 44.3,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 57.0,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Trans Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2327.38,
            },
            {
              name: "Magnesium",
              amount: 15.0,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 0.28,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 4.97,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 1.92,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.03,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 22.0,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.6,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.05,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.51,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Saturated Fat",
              amount: 0.13,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Vitamin B5",
              amount: 0.67,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 1038,
          name: "cheese",
          amount: 1.0,
          unit: "tbsp",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.86,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin A",
              amount: 20.75,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Sodium",
              amount: 60.0,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Iron",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 38.0,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.11,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.13,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 4.3,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 19.35,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.04,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.39,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 0.77,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.35,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.03,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.18,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Magnesium",
              amount: 2.05,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 1.35,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 0.18,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 1.59,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.03,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 5.2,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.06,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 53.2,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.73,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 1034053,
          name: "extra virgin olive oil",
          amount: 0.5,
          unit: "tbsp",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.97,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Sodium",
              amount: 0.14,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Iron",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 4.21,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 1.01,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 0.07,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 61.88,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 5.11,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Magnesium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            { name: "Fat", amount: 7.0, unit: "g", percentOfDailyNeeds: 24.93 },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.74,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 0.07,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 11215,
          name: "garlic",
          amount: 2.5,
          unit: "cloves",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin A",
              amount: 0.68,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Sodium",
              amount: 1.27,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Iron",
              amount: 0.13,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 11.48,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 2.34,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.13,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.13,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.09,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.09,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 30.08,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.16,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 11.18,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.08,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 1.74,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.22,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Net Carbohydrates",
              amount: 2.33,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Magnesium",
              amount: 1.88,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 0.04,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 2.48,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.48,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.02,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 13.57,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 1.07,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.05,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 10720420,
          name: "pasta",
          amount: 3.0,
          unit: "ounces",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.24,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Sodium",
              amount: 5.1,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Iron",
              amount: 1.11,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Vitamin B2",
              amount: 0.05,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 160.74,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.78,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.09,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 1.2,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.12,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.09,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Potassium",
              amount: 189.66,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 2.72,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 315.53,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 2.27,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Net Carbohydrates",
              amount: 60.78,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.15,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 15.31,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Trans Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2327.38,
            },
            {
              name: "Magnesium",
              amount: 45.08,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 1.28,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 63.51,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 11.09,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.48,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.25,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 17.86,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 53.75,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.08,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 1.45,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.37,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 1032009,
          name: "couple of pepper flakes",
          amount: 1.0,
          unit: "pinches",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin A",
              amount: 29.65,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Sodium",
              amount: 1.64,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Iron",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 0.3,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.11,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.02,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 1.95,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.03,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 0.28,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 0.07,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.03,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Trans Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2327.38,
            },
            {
              name: "Magnesium",
              amount: 0.15,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 0.05,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 0.33,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.02,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 1102047,
          name: "salt and pepper",
          amount: 1.0,
          unit: "servings",
          nutrients: [
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Sodium",
              amount: 193.79,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Fluoride",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 0.0,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Magnesium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            { name: "Fat", amount: 0.0, unit: "g", percentOfDailyNeeds: 24.93 },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 0.12,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 11291,
          name: "scallions",
          amount: 1.5,
          unit: "",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin A",
              amount: 179.46,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Sodium",
              amount: 2.88,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Iron",
              amount: 0.27,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 6.66,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 3.38,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.03,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 37.26,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.07,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.1,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 49.68,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.47,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 5.76,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.42,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 1.03,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 11.52,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.85,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Magnesium",
              amount: 3.6,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 0.03,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 1.32,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.33,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 12.96,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.11,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.09,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 14106,
          name: "white wine",
          amount: 1.0,
          unit: "tbsp",
          nutrients: [
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Sodium",
              amount: 0.75,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Fluoride",
              amount: 30.3,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Iron",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 2.7,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.06,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 10.65,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 12.3,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.14,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Choline",
              amount: 0.64,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.15,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.39,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Magnesium",
              amount: 1.5,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            { name: "Fat", amount: 0.0, unit: "g", percentOfDailyNeeds: 24.93 },
            {
              name: "Carbohydrates",
              amount: 0.39,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 1.54,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 1.35,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.01,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Vitamin B5",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
        {
          id: 99025,
          name: "bread crumbs",
          amount: 0.13,
          unit: "cup",
          nutrients: [
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 36.57,
            },
            {
              name: "Sodium",
              amount: 72.0,
              unit: "mg",
              percentOfDailyNeeds: 17.97,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 8.16,
            },
            {
              name: "Fluoride",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Iron",
              amount: 0.94,
              unit: "mg",
              percentOfDailyNeeds: 16.68,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 9.28,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 26.56,
            },
            {
              name: "Vitamin C",
              amount: 2.7,
              unit: "mg",
              percentOfDailyNeeds: 68.64,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 55.49,
            },
            {
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 55.2,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.9,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 21.14,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.01,
            },
            {
              name: "Potassium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.78,
            },
            {
              name: "Fiber",
              amount: 1.35,
              unit: "g",
              percentOfDailyNeeds: 26.92,
            },
            {
              name: "Calories",
              amount: 41.17,
              unit: "kcal",
              percentOfDailyNeeds: 27.17,
            },
            {
              name: "Sugar",
              amount: 0.45,
              unit: "g",
              percentOfDailyNeeds: 5.91,
            },
            {
              name: "Net Carbohydrates",
              amount: 9.45,
              unit: "g",
              percentOfDailyNeeds: 27.99,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 21.2,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Trans Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2327.38,
            },
            {
              name: "Magnesium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 17.35,
            },
            {
              name: "Fat",
              amount: 0.45,
              unit: "g",
              percentOfDailyNeeds: 24.93,
            },
            {
              name: "Carbohydrates",
              amount: 10.8,
              unit: "g",
              percentOfDailyNeeds: 27.9,
            },
            {
              name: "Protein",
              amount: 1.35,
              unit: "g",
              percentOfDailyNeeds: 33.68,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.82,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 16.27,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 8.58,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 1.13,
            },
            {
              name: "Calcium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 12.32,
            },
            {
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 80.51,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.31,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 10.67,
            },
            {
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 11.28,
            },
          ],
        },
      ],
      caloricBreakdown: {
        percentProtein: 12.29,
        percentFat: 26.61,
        percentCarbs: 61.1,
      },
      weightPerServing: { amount: 259, unit: "g" },
    },
    summary:
      'You can never have too many main course recipes, so give Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs a try. One serving contains <b>543 calories</b>, <b>17g of protein</b>, and <b>16g of fat</b>. For <b>$1.57 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. This recipe serves 2. A mixture of butter, white wine, pasta, and a handful of other ingredients are all it takes to make this recipe so yummy. 209 people have tried and liked this recipe. It is brought to you by fullbellysisters.blogspot.com. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 83%</b>, which is tremendous. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1230187">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>, <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1229807">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>, and <a href="https://spoonacular.com/recipes/pasta-with-garlic-scallions-cauliflower-breadcrumbs-1229669">Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs</a>.',
    cuisines: [],
    dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
    diets: [],
    occasions: [],
    winePairing: {
      pairedWines: [],
      pairingText:
        "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
      productMatches: [],
    },
    instructions: "",
    analyzedInstructions: [],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
  },
];

export default detail;
