const recipes = [
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 6,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 73,
    healthScore: 7,
    creditsText: "Afrolems",
    license: "CC BY 4.0",
    sourceName: "Afrolems",
    pricePerServing: 51.09,
    extendedIngredients: [
      {
        id: 9087,
        aisle: "Dried Fruits",
        image: "dates.jpg",
        consistency: "SOLID",
        name: "dates",
        nameClean: "dates",
        original: "2 pieces of dates (remove the seeds)",
        originalName: "dates (remove the seeds)",
        amount: 2,
        unit: "pieces",
        meta: ["(remove the seeds)"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 1214,
        aisle: "Baking",
        image: "evaporated-milk.png",
        consistency: "SOLID",
        name: "evaporated milk",
        nameClean: "evaporated milk",
        original: "7 tablespoons of evaporated milk",
        originalName: "evaporated milk",
        amount: 7,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 7,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 7,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 11216,
        aisle: "Produce",
        image: "ginger.png",
        consistency: "SOLID",
        name: "ginger",
        nameClean: "ginger",
        original: "1/4 teaspoon of grated ginger",
        originalName: "grated ginger",
        amount: 0.25,
        unit: "teaspoon",
        meta: ["grated"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 10114412,
        aisle: "Frozen",
        image: "crushed-ice.png",
        consistency: "SOLID",
        name: "ice",
        nameClean: "crushed ice cubes",
        original: "1/4 cup of crushed ice.",
        originalName: "crushed ice",
        amount: 0.25,
        unit: "cup",
        meta: ["crushed"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 9326,
        aisle: "Produce",
        image: "watermelon.png",
        consistency: "SOLID",
        name: "blended watermelon",
        nameClean: "watermelon",
        original: "1 cup of blended watermelon",
        originalName: "blended watermelon",
        amount: 1,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 152,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
    ],
    id: 716252,
    title: "Milky Watermelon Drink",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl: "http://www.afrolems.com/2016/01/29/milky-watermelon-drink/",
    image: "https://spoonacular.com/recipeImages/716252-556x370.jpg",
    imageType: "jpg",
    summary:
      'Milky Watermelon Drink might be a good recipe to expand your beverage recipe box. One portion of this dish contains approximately <b>8g of protein</b>, <b>8g of fat</b>, and a total of <b>193 calories</b>. This recipe serves 1. For <b>51 cents per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. Head to the store and pick up dates, blended watermelon, ice, and a few other things to make it today. It will be a hit at your <b>Summer</b> event. 73 people have tried and liked this recipe. It is brought to you by Afrolems. It is a good option if you\'re following a <b>gluten free and lacto ovo vegetarian</b> diet. From preparation to the plate, this recipe takes about <b>45 minutes</b>. With a spoonacular <b>score of 58%</b>, this dish is solid. Try <a href="https://spoonacular.com/recipes/watermelon-mocktail-drink-716380">Watermelon Mocktail Drink</a>, <a href="https://spoonacular.com/recipes/quick-watermelon-summer-drink-582115">Quick Watermelon Summer Drink</a>, and <a href="https://spoonacular.com/recipes/watermelon-iced-tea-drink-recipe-27499">Watermelon Iced Tea Drink Recipe</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["beverage", "drink"],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: ["summer"],
    instructions:
      "Blend all ingredients together till smooth and serve chilled.P:S – If you are wondering where to buy dates, check out supermarkets or the hausa traders at a market. They are more likely to have dates. Does anyone know what dates are called in Hausa? Please leave a comment and help others",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Blend all ingredients together till smooth and serve chilled.P:S – If you are wondering where to buy dates, check out supermarkets or the hausa traders at a market. They are more likely to have dates. Does anyone know what dates are called in Hausa? Please leave a comment and help others",
            ingredients: [
              {
                id: 9087,
                name: "dates",
                localizedName: "dates",
                image: "dates.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/milky-watermelon-drink-716252",
  },
  {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 10,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 9,
    healthScore: 6,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 166.83,
    extendedIngredients: [
      {
        id: 1123,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg.png",
        consistency: "SOLID",
        name: "eggs",
        nameClean: "egg",
        original: "4 large eggs",
        originalName: "eggs",
        amount: 4,
        unit: "large",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "large",
            unitLong: "larges",
          },
          metric: {
            amount: 4,
            unitShort: "large",
            unitLong: "larges",
          },
        },
      },
      {
        id: 10719335,
        aisle: "Baking",
        image: "sugar-in-bowl.png",
        consistency: "SOLID",
        name: "granulated sugar",
        nameClean: "granulated sugar",
        original: "1/3 cup granulated sugar",
        originalName: "granulated sugar",
        amount: 0.33333334,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.33333334,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 66.667,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 10719335,
        aisle: "Baking",
        image: "sugar-in-bowl.png",
        consistency: "SOLID",
        name: "granulated sugar",
        nameClean: "granulated sugar",
        original: "1/2 cup granulated sugar",
        originalName: "granulated sugar",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 100,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 9316,
        aisle: "Produce",
        image: "strawberries.png",
        consistency: "SOLID",
        name: "strawberries",
        nameClean: "strawberries",
        original: "strawberries",
        originalName: "strawberries",
        amount: 6,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 6,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 6,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 1052050,
        aisle: "Baking",
        image: "vanilla.jpg",
        consistency: "SOLID",
        name: "vanilla",
        nameClean: "vanilla",
        original: "1 tsp vanilla",
        originalName: "vanilla",
        amount: 1,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 1011077,
        aisle: "Milk, Eggs, Other Dairy",
        image: "milk.png",
        consistency: "LIQUID",
        name: "milk",
        nameClean: "whole milk",
        original: "2 cups whole milk",
        originalName: "whole milk",
        amount: 2,
        unit: "cups",
        meta: ["whole"],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 488,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 638717,
    title: "Chinese Steamed Flan",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl: "http://www.foodista.com/recipe/GNDGXPZK/chinese-steamed-flan",
    image: "https://spoonacular.com/recipeImages/638717-556x370.jpg",
    imageType: "jpg",
    summary:
      'Chinese Steamed Flan is a dessert that serves 6. Watching your figure? This gluten free and lacto ovo vegetarian recipe has <b>252 calories</b>, <b>8g of protein</b>, and <b>6g of fat</b> per serving. For <b>$1.67 per serving</b>, this recipe <b>covers 14%</b> of your daily requirements of vitamins and minerals. Only a few people made this recipe, and 9 would say it hit the spot. It is a <b>rather inexpensive</b> recipe for fans of Chinese food. It is brought to you by Foodista. Head to the store and pick up strawberries, granulated sugar, milk, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. Overall, this recipe earns a <b>solid spoonacular score of 47%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/how-to-cook-leche-flan-steamed-crme-caramel-478107">How to cook: Leche flan (steamed crème caramel)</a>, <a href="https://spoonacular.com/recipes/chinese-steamed-fish-40745">Chinese Steamed Fish</a>, and <a href="https://spoonacular.com/recipes/ma-lai-go-chinese-steamed-cake-1075533">Ma Lai Go Chinese Steamed Cake</a>.',
    cuisines: ["Chinese", "Asian"],
    dishTypes: ["dessert"],
    diets: ["gluten free", "lacto ovo vegetarian"],
    occasions: [],
    instructions:
      "<ol><li>For caramel:</li><li>Spread sugar evenly in the bottom of a heavy saucepan and place over medium-low heat. It may take several minutes before the sugar begins to melt. Without stirring, watch the sugar closely as it begins to liquefy at the edges.  It will slowly turn from a yellow to a golden and finally to a brown caramel sauce.</li><li>When the liquefied sugar is turning from golden to brown, immediately remove the saucepan from the heat. Watch carefully!  (If you miss this point, the sugar will quickly turn too dark and you will have to start all over again).  Immediately pour liquid caramel into 6 3-1/2 inch ramekins and swirl to cover bottom evenly. The caramel hardens rapidly, so work quickly.  Set aside.</li><li>For flan:</li><li>Place 2 inches of water on the bottom portion of steamer.  Cover and allow water to come to a boil.  In the meantime, heat milk and sugar in a saucepan until just warmed and sugar has dissolved.  Whisk eggs and vanilla in a large bowl until blended.  Slowly pour warmed milk into the eggs, beating until well combined.  Scoop off foam and discard.  Ladle into prepared ramekins and place into steamer.</li><li>Turn down heat  this is very important  to medium and steam for 15 minutes.  Remove and allow to cool.  Once cool, cover and refrigerate overnight.  When ready to serve, carefully run a knife around the inside each ramekin to loosen the flan. Place a plate on top of the flan and invert until flan pops out.  Serve with sliced strawberries.</li></ol>",
    analyzedInstructions: [
      {
        name: "For caramel",
        steps: [],
      },
      {
        name: "Spread sugar evenly in the bottom of a heavy saucepan and place over medium-low heat. It may take several minutes before the sugar begins to melt. Without stirring, watch the sugar closely as it begins to liquefy at the edges.  It will slowly turn from a yellow to a golden and finally to a brown caramel sauce.When the liquefied sugar is turning from golden to brown, immediately remove the saucepan from the heat. Watch carefully!  (If you miss this point, the sugar will quickly turn too dark and you will have to start all over again).  Immediately pour liquid caramel into 6 3-1/2 inch ramekins and swirl to cover bottom evenly. The caramel hardens rapidly, so work quickly.  Set aside.For flan",
        steps: [
          {
            number: 1,
            step: "Place 2 inches of water on the bottom portion of steamer.  Cover and allow water to come to a boil.  In the meantime, heat milk and sugar in a saucepan until just warmed and sugar has dissolved.",
            ingredients: [
              {
                id: 19335,
                name: "sugar",
                localizedName: "sugar",
                image: "sugar-in-bowl.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Whisk eggs and vanilla in a large bowl until blended.  Slowly pour warmed milk into the eggs, beating until well combined.  Scoop off foam and discard.  Ladle into prepared ramekins and place into steamer.Turn down heat  this is very important  to medium and steam for 15 minutes.",
            ingredients: [
              {
                id: 1052050,
                name: "vanilla",
                localizedName: "vanilla",
                image: "vanilla.jpg",
              },
              {
                id: 1123,
                name: "egg",
                localizedName: "egg",
                image: "egg.png",
              },
              {
                id: 1077,
                name: "milk",
                localizedName: "milk",
                image: "milk.png",
              },
            ],
            equipment: [
              {
                id: 404781,
                name: "ramekin",
                localizedName: "ramekin",
                image: "ramekin.jpg",
              },
              {
                id: 404630,
                name: "ladle",
                localizedName: "ladle",
                image: "ladle.jpg",
              },
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image: "whisk.png",
              },
              {
                id: 404783,
                name: "bowl",
                localizedName: "bowl",
                image: "bowl.jpg",
              },
            ],
            length: {
              number: 15,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Remove and allow to cool.  Once cool, cover and refrigerate overnight.  When ready to serve, carefully run a knife around the inside each ramekin to loosen the flan.",
            ingredients: [],
            equipment: [
              {
                id: 404781,
                name: "ramekin",
                localizedName: "ramekin",
                image: "ramekin.jpg",
              },
              {
                id: 404745,
                name: "knife",
                localizedName: "knife",
                image: "chefs-knife.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Place a plate on top of the flan and invert until flan pops out.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 5,
            step: "Serve with sliced strawberries.",
            ingredients: [
              {
                id: 9316,
                name: "strawberries",
                localizedName: "strawberries",
                image: "strawberries.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/chinese-steamed-flan-638717",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 7,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 56,
    creditsText: "foodista.com",
    sourceName: "foodista.com",
    pricePerServing: 312.19,
    extendedIngredients: [
      {
        id: 11485,
        aisle: "Produce",
        image: "butternut-squash.jpg",
        consistency: "SOLID",
        name: "butternut squash",
        nameClean: "butternut squash",
        original: "1 butternut squash, peeled and cut up into squares",
        originalName: "butternut squash, peeled and cut up into squares",
        amount: 1,
        unit: "",
        meta: ["peeled"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "SOLID",
        name: "carrot",
        nameClean: "carrot",
        original: "1 large carrot, cut up",
        originalName: "carrot, cut up",
        amount: 1,
        unit: "large",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "large",
            unitLong: "large",
          },
          metric: {
            amount: 1,
            unitShort: "large",
            unitLong: "large",
          },
        },
      },
      {
        id: 11167,
        aisle: "Produce",
        image: "corn-on-the-cob.jpg",
        consistency: "SOLID",
        name: "ears of corn",
        nameClean: "corn on the cob",
        original: "3 ears of corn",
        originalName: "ears of corn",
        amount: 3,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 3,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 3,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2045,
        aisle: "Spices and Seasonings",
        image: "dill.jpg",
        consistency: "SOLID",
        name: "dill",
        nameClean: "dill",
        original: "1 bunch of fresh dill",
        originalName: "fresh dill",
        amount: 1,
        unit: "bunch",
        meta: ["fresh"],
        measures: {
          us: {
            amount: 1,
            unitShort: "bunch",
            unitLong: "bunch",
          },
          metric: {
            amount: 1,
            unitShort: "bunch",
            unitLong: "bunch",
          },
        },
      },
      {
        id: 1053,
        aisle: "Milk, Eggs, Other Dairy",
        image: "fluid-cream.jpg",
        consistency: "LIQUID",
        name: "heavy cream",
        nameClean: "cream",
        original: "1/4 cup of heavy cream",
        originalName: "heavy cream",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.5,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10011282,
        aisle: "Produce",
        image: "red-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "red onion",
        original: "2 tablespoons finely diced red onion",
        originalName: "finely diced red onion",
        amount: 2,
        unit: "tablespoons",
        meta: ["diced", "red", "finely"],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 15076,
        aisle: "Seafood",
        image: "salmon.png",
        consistency: "SOLID",
        name: "salmon",
        nameClean: "salmon",
        original: "12 ounces of salmon, chopped with a sharp knife",
        originalName: "salmon, chopped with a sharp knife",
        amount: 12,
        unit: "ounces",
        meta: ["with a sharp knife", "chopped"],
        measures: {
          us: {
            amount: 12,
            unitShort: "oz",
            unitLong: "ounces",
          },
          metric: {
            amount: 340.194,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "salt and pepper",
        originalName: "salt and pepper",
        amount: 4,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "scallions",
        nameClean: "spring onions",
        original: "3 sprigs of scallions, cut up",
        originalName: "scallions, cut up",
        amount: 3,
        unit: "sprigs",
        meta: [],
        measures: {
          us: {
            amount: 3,
            unitShort: "sprigs",
            unitLong: "sprigs",
          },
          metric: {
            amount: 3,
            unitShort: "sprigs",
            unitLong: "sprigs",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "1/4 cup water",
        originalName: "water",
        amount: 0.25,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 59.147,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
    ],
    id: 659056,
    title: "Salmon Butternut Squash Corn Chowder",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl:
      "http://www.foodista.com/recipe/QMRHYRGG/salmon-butternut-squash-corn-chowder",
    image: "https://spoonacular.com/recipeImages/659056-556x370.jpg",
    imageType: "jpg",
    summary:
      'Salmon Butternut Squash Corn Chowder might be just the main course you are searching for. This gluten free and pescatarian recipe serves 4 and costs <b>$3.12 per serving</b>. One portion of this dish contains roughly <b>22g of protein</b>, <b>12g of fat</b>, and a total of <b>326 calories</b>. 2 people were impressed by this recipe. If you have butternut squash, onion, water, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is brought to you by Foodista. Overall, this recipe earns an <b>amazing spoonacular score of 86%</b>. Try <a href="https://spoonacular.com/recipes/salmon-butternut-squash-corn-chowder-1288581">Salmon Butternut Squash Corn Chowder</a>, <a href="https://spoonacular.com/recipes/corn-and-butternut-squash-chowder-105432">Corn and Butternut Squash Chowder</a>, and <a href="https://spoonacular.com/recipes/curried-coconut-turkey-chowder-with-corn-and-butternut-squash-12560">Curried Coconut Turkey Chowder With Corn And Butternut Squash</a> for similar recipes.',
    cuisines: [],
    dishTypes: ["lunch", "soup", "main course", "main dish", "dinner"],
    diets: ["gluten free", "pescatarian"],
    occasions: [],
    instructions:
      "<ol><li>Pour water into a medium-size soup pot and start boiling on a low flame. Chop up the onions, butternut squash, carrots, corn, along with the scallions and dill and add them to the pot. Cover and let cook on a low flame for 30 minutes. Taste and add salt and pepper. Cut up the salmon and add it to the soup, along with the cream. Let cook for another 20 minutes, taste again and enjoy!</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Pour water into a medium-size soup pot and start boiling on a low flame. Chop up the onions, butternut squash, carrots, corn, along with the scallions and dill and add them to the pot. Cover and let cook on a low flame for 30 minutes. Taste and add salt and pepper.",
            ingredients: [
              {
                id: 11485,
                name: "butternut squash",
                localizedName: "butternut squash",
                image: "butternut-squash.jpg",
              },
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 11291,
                name: "green onions",
                localizedName: "green onions",
                image: "spring-onions.jpg",
              },
              {
                id: 11124,
                name: "carrot",
                localizedName: "carrot",
                image: "sliced-carrot.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
              {
                id: 11168,
                name: "corn",
                localizedName: "corn",
                image: "corn.png",
              },
              {
                id: 2045,
                name: "dill",
                localizedName: "dill",
                image: "dill.jpg",
              },
              {
                id: 0,
                name: "soup",
                localizedName: "soup",
                image: "",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
            length: {
              number: 30,
              unit: "minutes",
            },
          },
          {
            number: 2,
            step: "Cut up the salmon and add it to the soup, along with the cream.",
            ingredients: [
              {
                id: 15076,
                name: "salmon",
                localizedName: "salmon",
                image: "salmon.png",
              },
              {
                id: 1053,
                name: "cream",
                localizedName: "cream",
                image: "fluid-cream.jpg",
              },
              {
                id: 0,
                name: "soup",
                localizedName: "soup",
                image: "",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Let cook for another 20 minutes, taste again and enjoy!",
            ingredients: [],
            equipment: [],
            length: {
              number: 20,
              unit: "minutes",
            },
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/salmon-butternut-squash-corn-chowder-659056",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: true,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 125,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 100,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 732.92,
    extendedIngredients: [
      {
        id: 10020444,
        aisle: "Pasta and Rice",
        image: "rice-white-long-grain-or-basmatii-cooked.jpg",
        consistency: "SOLID",
        name: "basmati rice",
        nameClean: "basmati rice",
        original: "2 cups basmati rice, rinse several times in cold water and",
        originalName: "basmati rice, rinse several times in cold water and",
        amount: 2,
        unit: "cups",
        meta: ["cold"],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 370,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 12087,
        aisle: "Nuts",
        image: "cashews.jpg",
        consistency: "SOLID",
        name: "cashews",
        nameClean: "cashews",
        original: "1/4 cup cashews, halved",
        originalName: "cashews, halved",
        amount: 0.25,
        unit: "cup",
        meta: ["halved"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 32.25,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 12104,
        aisle: "Produce",
        image: "coconut.jpg",
        consistency: "SOLID",
        name: "coconut",
        nameClean: "coconut",
        original: "1/4 cup grated fresh coconut",
        originalName: "grated fresh coconut",
        amount: 0.25,
        unit: "cup",
        meta: ["fresh", "grated"],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 20,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10211216,
        aisle: "Produce",
        image: "ginger.png",
        consistency: "SOLID",
        name: "ginger",
        nameClean: "fresh ginger",
        original: "1 tablespoon grated fresh ginger",
        originalName: "grated fresh ginger",
        amount: 1,
        unit: "tablespoon",
        meta: ["fresh", "grated"],
        measures: {
          us: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "1 clove garlic, chopped",
        originalName: "garlic, chopped",
        amount: 1,
        unit: "clove",
        meta: ["chopped"],
        measures: {
          us: {
            amount: 1,
            unitShort: "clove",
            unitLong: "clove",
          },
          metric: {
            amount: 1,
            unitShort: "clove",
            unitLong: "clove",
          },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "green onion",
        nameClean: "spring onions",
        original: "1/2 cup thinly sliced green onion",
        originalName: "thinly sliced green onion",
        amount: 0.5,
        unit: "cup",
        meta: ["thinly sliced"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 50,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 4042,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "peanut-oil.jpg",
        consistency: "LIQUID",
        name: "peanut oil",
        nameClean: "peanut oil",
        original:
          "3 tablespoons tablespoons peanut oil, plus 1 for the cashews",
        originalName: "tablespoons peanut oil, plus 1 for the cashews",
        amount: 3,
        unit: "tablespoons",
        meta: ["for the cashews"],
        measures: {
          us: {
            amount: 3,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 3,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "SOLID",
        name: "salt and pepper",
        nameClean: "salt and pepper",
        original: "salt and fresh pepper",
        originalName: "salt and fresh pepper",
        amount: 1,
        unit: "serving",
        meta: ["fresh"],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
      {
        id: 12117,
        aisle: "Canned and Jarred",
        image: "coconut-milk.png",
        consistency: "LIQUID",
        name: "coconut milk",
        nameClean: "unsweetened coconut milk",
        original: "2 cups unsweetened coconut milk",
        originalName: "unsweetened coconut milk",
        amount: 2,
        unit: "cups",
        meta: ["unsweetened"],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 480,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "2 cups water",
        originalName: "water",
        amount: 2,
        unit: "cups",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 473.176,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 10511282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "yellow onion",
        original: "1 medium yellow onion, peeled, halved and thinly sliced",
        originalName: "yellow onion, peeled, halved and thinly sliced",
        amount: 1,
        unit: "medium",
        meta: ["yellow", "peeled", "halved", "thinly sliced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "medium",
            unitLong: "medium",
          },
          metric: {
            amount: 1,
            unitShort: "medium",
            unitLong: "medium",
          },
        },
      },
    ],
    id: 648780,
    title: "Kate's Coconut-Cashew Basmati Rice Salad",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "http://www.foodista.com/recipe/8KB4VT3P/kates-coconut-cashew-basmati-rice-salad",
    image: "https://spoonacular.com/recipeImages/648780-556x370.jpg",
    imageType: "jpg",
    summary:
      'You can never have too many main course recipes, so give Kate\'s Coconut-Cashew Basmati Rice Salad a try. This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe serves 1 and costs <b>$7.33 per serving</b>. One serving contains <b>3145 calories</b>, <b>46g of protein</b>, and <b>180g of fat</b>. 2 people found this recipe to be tasty and satisfying. If you have basmati rice, ginger, garlic, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 93%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/coconut-basmati-rice-114122">Coconut Basmati Rice</a>, <a href="https://spoonacular.com/recipes/coconut-basmati-rice-114117">Coconut Basmati Rice</a>, and <a href="https://spoonacular.com/recipes/coconut-basmati-rice-114119">Coconut Basmati Rice</a>.',
    cuisines: [],
    dishTypes: [
      "side dish",
      "lunch",
      "salad",
      "main course",
      "main dish",
      "dinner",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    instructions:
      "<ol><li>Heat oil in a medium saucepan. Add onion, garlic and ginger and cook until soft. Add the drained rice, salt and pepper and cook for 3 to 4 minutes. While the rice is cooking, heat the remaining tablespoon oil in a small saute pan over medium heat. Add the cashews and cook until lightly golden brown. Drain on paper towels.    Place coconut milk and water in a medium saucepan and bring to a simmer. Add the hot liquid to the rice and bring to a boil. Reduce the heat, cover and cook for about 15 to 20 minutes. When the rice is cooked, remove from the oven and fold</li><li>Make sure you salt this well, otherwise it can be on the bland side. Yum!</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Heat oil in a medium saucepan.",
            ingredients: [
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Add onion, garlic and ginger and cook until soft.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11216,
                name: "ginger",
                localizedName: "ginger",
                image: "ginger.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Add the drained rice, salt and pepper and cook for 3 to 4 minutes. While the rice is cooking, heat the remaining tablespoon oil in a small saute pan over medium heat.",
            ingredients: [
              {
                id: 1102047,
                name: "salt and pepper",
                localizedName: "salt and pepper",
                image: "salt-and-pepper.jpg",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [
              {
                id: 404645,
                name: "frying pan",
                localizedName: "frying pan",
                image: "pan.png",
              },
            ],
            length: {
              number: 3,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Add the cashews and cook until lightly golden brown.",
            ingredients: [
              {
                id: 12087,
                name: "cashews",
                localizedName: "cashews",
                image: "cashews.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Drain on paper towels.",
            ingredients: [],
            equipment: [
              {
                id: 405895,
                name: "paper towels",
                localizedName: "paper towels",
                image: "paper-towels.jpg",
              },
            ],
          },
          {
            number: 6,
            step: "Place coconut milk and water in a medium saucepan and bring to a simmer.",
            ingredients: [
              {
                id: 12118,
                name: "coconut milk",
                localizedName: "coconut milk",
                image: "coconut-milk.png",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [
              {
                id: 404669,
                name: "sauce pan",
                localizedName: "sauce pan",
                image: "sauce-pan.jpg",
              },
            ],
          },
          {
            number: 7,
            step: "Add the hot liquid to the rice and bring to a boil. Reduce the heat, cover and cook for about 15 to 20 minutes. When the rice is cooked, remove from the oven and fold",
            ingredients: [
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 15,
              unit: "minutes",
            },
          },
          {
            number: 8,
            step: "Make sure you salt this well, otherwise it can be on the bland side. Yum!",
            ingredients: [
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/kates-coconut-cashew-basmati-rice-salad-648780",
  },
  {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 11,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 30,
    creditsText: "foodista.com",
    sourceName: "foodista.com",
    pricePerServing: 217.17,
    extendedIngredients: [
      {
        id: 5062,
        aisle: "Meat",
        image: "chicken-breasts.png",
        consistency: "SOLID",
        name: "whl chicken breasts",
        nameClean: "chicken breast",
        original: "2 whl chicken breasts",
        originalName: "whl chicken breasts",
        amount: 2,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 10511819,
        aisle: "Produce",
        image: "red-chili.jpg",
        consistency: "SOLID",
        name: "whl chili pepper",
        nameClean: "red chili pepper",
        original: "8 whl dried red chili pepper",
        originalName: "whl dried red chili pepper",
        amount: 8,
        unit: "",
        meta: ["dried", "red"],
        measures: {
          us: {
            amount: 8,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 8,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 42289,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vegetable-oil.jpg",
        consistency: "LIQUID",
        name: "corn oil",
        nameClean: "corn oil",
        original: "6 tablespoons Peanut or corn oil",
        originalName: "Peanut or corn oil",
        amount: 6,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 6,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 6,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 20027,
        aisle: "Baking",
        image: "white-powder.jpg",
        consistency: "SOLID",
        name: "cornstarch",
        nameClean: "corn starch",
        original: "1 teaspoon Cornstarch",
        originalName: "Cornstarch",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 1124,
        aisle: "Milk, Eggs, Other Dairy",
        image: "egg-white.jpg",
        consistency: "SOLID",
        name: "egg white",
        nameClean: "egg whites",
        original: "1 Egg white",
        originalName: "Egg white",
        amount: 1,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 16092,
        aisle: "Nuts",
        image: "peanuts.png",
        consistency: "SOLID",
        name: "roasted peanuts",
        nameClean: "roasted peanuts",
        original: "1/2 cup Roasted peanuts",
        originalName: "Roasted peanuts",
        amount: 0.5,
        unit: "cup",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 73,
            unitShort: "g",
            unitLong: "grams",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "salt",
        originalName: "salt",
        amount: 4,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 11291,
        aisle: "Produce",
        image: "spring-onions.jpg",
        consistency: "SOLID",
        name: "scallions",
        nameClean: "spring onions",
        original: "2 Scallions, cut in 1/4 in",
        originalName: "Scallions, cut in 1/4 in",
        amount: 2,
        unit: "",
        meta: ["cut in 1/4 in"],
        measures: {
          us: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 2,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 4058,
        aisle: "Ethnic Foods",
        image: "sesame-oil.png",
        consistency: "LIQUID",
        name: "sesame oil",
        nameClean: "sesame oil",
        original: "1 teaspoon Sesame oil",
        originalName: "Sesame oil",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 16124,
        aisle: "Condiments",
        image: "soy-sauce.jpg",
        consistency: "LIQUID",
        name: "soy sauce",
        nameClean: "soy sauce",
        original: "2 tablespoons Soy sauce",
        originalName: "Soy sauce",
        amount: 2,
        unit: "tablespoons",
        meta: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "Water",
        originalName: "Water",
        amount: 4,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
      {
        id: 2053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "vinegar-(white).jpg",
        consistency: "LIQUID",
        name: "distilled vinegar",
        nameClean: "distilled white vinegar",
        original: "1 teaspoon Distilled white vinegar",
        originalName: "Distilled white vinegar",
        amount: 1,
        unit: "teaspoon",
        meta: ["white"],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
    ],
    id: 649131,
    title: "Kung Po Chicken",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "http://www.foodista.com/recipe/HDCGFZVF/kung-po-chicken",
    image: "https://spoonacular.com/recipeImages/649131-556x370.jpg",
    imageType: "jpg",
    summary:
      'If you have roughly <b>45 minutes</b> to spend in the kitchen, Kung Po Chicken might be a spectacular <b>gluten free, dairy free, and ketogenic</b> recipe to try. For <b>$2.17 per serving</b>, you get a main course that serves 4. One serving contains <b>478 calories</b>, <b>33g of protein</b>, and <b>34g of fat</b>. 2 people were impressed by this recipe. Head to the store and pick up water, cornstarch, salt, and a few other things to make it today. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 73%</b>. This score is solid. Similar recipes include <a href="https://spoonacular.com/recipes/kung-pao-popeye-kung-pao-chicken-made-with-popeyes-nuggets-1196129">Kung Pao Popeye (Kung Pao Chicken Made with Popeye\'s Nuggets)</a>, <a href="https://spoonacular.com/recipes/kung-pao-popeye-kung-pao-chicken-made-with-popeyes-nuggets-95410">Kung Pao Popeye (Kung Pao Chicken Made with Popeye\'s Nuggets)</a>, and <a href="https://spoonacular.com/recipes/kung-po-chicken-685079">Kung Po Chicken</a>.',
    cuisines: [],
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    diets: ["gluten free", "dairy free", "ketogenic"],
    occasions: [],
    instructions:
      "<ol><li>Cut chicken into 1/2 inch cubes. You will have about 1-1/2 cups. Combine the egg white, cornstarch, soy sauce and 1 tbsp water and add to chicken cubes, mixing well. Set aside for 30 minutes. Wipe the chicli peppers clean with a wet towel. Remove the tops and set aside on plate with scallions Combine the sauce ingredients in a cup. Set aside near cooking area. Place a strainer over a pot near the cooking area. Heat a wok over moderate heat until it is very hot. Add the peanut oil and heat to about 300. Mix the chicken again and add to the hot oil. Raise the heat to</li></ol>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Cut chicken into 1/2 inch cubes. You will have about 1-1/2 cups.",
            ingredients: [
              {
                id: 0,
                name: "chicken",
                localizedName: "chicken",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 2,
            step: "Combine the egg white, cornstarch, soy sauce and 1 tbsp water and add to chicken cubes, mixing well. Set aside for 30 minutes. Wipe the chicli peppers clean with a wet towel.",
            ingredients: [
              {
                id: 20027,
                name: "corn starch",
                localizedName: "corn starch",
                image: "white-powder.jpg",
              },
              {
                id: 1124,
                name: "egg whites",
                localizedName: "egg whites",
                image: "egg-white.jpg",
              },
              {
                id: 16124,
                name: "soy sauce",
                localizedName: "soy sauce",
                image: "soy-sauce.jpg",
              },
              {
                id: 0,
                name: "chicken",
                localizedName: "chicken",
                image: "whole-chicken.jpg",
              },
              {
                id: 10111333,
                name: "peppers",
                localizedName: "peppers",
                image: "green-pepper.jpg",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [],
            length: {
              number: 30,
              unit: "minutes",
            },
          },
          {
            number: 3,
            step: "Remove the tops and set aside on plate with scallions",
            ingredients: [
              {
                id: 11291,
                name: "green onions",
                localizedName: "green onions",
                image: "spring-onions.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: "Combine the sauce ingredients in a cup. Set aside near cooking area.",
            ingredients: [
              {
                id: 0,
                name: "sauce",
                localizedName: "sauce",
                image: "",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Place a strainer over a pot near the cooking area.",
            ingredients: [],
            equipment: [
              {
                id: 405600,
                name: "sieve",
                localizedName: "sieve",
                image: "strainer.png",
              },
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 6,
            step: "Heat a wok over moderate heat until it is very hot.",
            ingredients: [],
            equipment: [
              {
                id: 404666,
                name: "wok",
                localizedName: "wok",
                image: "wok.png",
              },
            ],
          },
          {
            number: 7,
            step: "Add the peanut oil and heat to about 30",
            ingredients: [
              {
                id: 4042,
                name: "peanut oil",
                localizedName: "peanut oil",
                image: "peanut-oil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Mix the chicken again and add to the hot oil. Raise the heat to",
            ingredients: [
              {
                id: 0,
                name: "chicken",
                localizedName: "chicken",
                image: "whole-chicken.jpg",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl: "https://spoonacular.com/kung-po-chicken-649131",
  },
];

export default recipes;
